// const Profile={
//     noOfPost:1995,
//     noOfFollowers:564,
//     noOffollowing:4,
//     channelName:"Apna college",
//     userName:"sharadha khapra",
// };
// console.log(Profile);

// let a =3;
// if(a%2==0){
//     console.log(" is even")
// }else{
//     console.log("is odd")
// }

// let score=prompt(21);
// if(score==12){
//     console.log(pass);
// }

// for(let i=1; i<=100;i++){
// if(i%2==0){
//     console.log(i)
// }
// }

let gameno=24;
let userno = 6;
while(userno==gameno){
    if(userno > gameno && userno > 0){
        console.log("high");
    }
    if(userno < gameno && userno > 0){
        console.log("less");
    }
    else{
        console.log("invalid")
    }
}console.log(gameno);